workflows:
  ios-simulator-build:
    name: iOS Simulator Build
    environment:
      flutter: stable
      cocoapods: default
      xcode: latest
    scripts:
      - name: Set up Flutter
        script: |
          flutter doctor -v
          flutter pub get

      - name: Ensure Podfile and Xcode deployment target are correct
        script: |
          cd ios

          # Step 1: Edit Podfile
          if [ ! -f "Podfile" ]; then
            echo "Podfile not found, creating one."
            echo "platform :ios, '13.0'" > Podfile
            echo "target 'Runner' do" >> Podfile
            echo "end" >> Podfile
          else
            echo "Editing Podfile to set iOS 13.0"
            sed -i.bak "s/platform :ios, '[^']*'/platform :ios, '13.0'/g" Podfile
            if ! grep -q "platform :ios" Podfile; then
              echo "platform :ios, '13.0'" | cat - Podfile > temp && mv temp Podfile
            fi
          fi

          # Step 2: Edit project.pbxproj to set deployment target
          echo "Updating Xcode project minimum iOS version"
          pbxproj="Runner.xcodeproj/project.pbxproj"
          sed -i.bak "s/IPHONEOS_DEPLOYMENT_TARGET = [0-9.]*/IPHONEOS_DEPLOYMENT_TARGET = 13.0/g" "$pbxproj"

          cat Podfile
          cd ..

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Build for iOS Simulator
        script: |
          flutter build ios --simulator

    artifacts:
      - build/ios/iphonesimulator/Runner.app
