workflows:
  ios-simulator-build:
    name: iOS Simulator Build
    environment:
      flutter: stable
      cocoapods: default
      xcode: latest
    scripts:
      - name: Set up Flutter
        script: |
          flutter doctor -v
          flutter pub get

      - name: Ensure Podfile exists and set platform
        script: |
          cd ios
          if [ ! -f "Podfile" ]; then
            echo "Podfile not found, creating a basic one."
            echo "platform :ios, '13.0'" > Podfile
            echo "target 'Runner' do" >> Podfile
            echo "end" >> Podfile
          else
            echo "Podfile found, setting platform to 13.0."
            sed -i '' "s/platform :ios, '.*'/platform :ios, '13.0'/g" Podfile
          fi
          cat Podfile
          cd ..

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Build for iOS Simulator
        script: |
          flutter build ios --simulator

    artifacts:
      - build/ios/iphonesimulator/Runner.app
