name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: 🎉 iOS Build
    runs-on: macos-latest
    steps:
      - name: Checkout latest commit
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures the latest commit is pulled

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Clean Flutter & pub cache
        run: |
          flutter clean
          flutter pub cache repair

      - name: Get latest dependencies
        run: flutter pub get

      - name: Select Xcode Version
        run: sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer

      - name: Install CocoaPods dependencies
        run: |
          if [ -f "Podfile" ]; then
            pod deintegrate
            pod install --repo-update --verbose
          else
            echo "Podfile not found, skipping pod install"
          fi
        working-directory: ios

      - name: Build iOS release
        run: flutter build ios --release --no-codesign

      - name: Prepare IPA file
        run: |
          mkdir -p Payload
          mv Runner.app Payload
          zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "This is first release"
